apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    build.appstudio.openshift.io/application: my-application-3
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: my-application-3-nodejs-sample
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: my-application-3-nodejs-sample
  namespace: pshivpuj
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: my-application-3-nodejs-sample
status:
  configuration:
    generatedName: ""
