apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: my-application-3-nodejs-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-application-3-nodejs-sample
    app.kubernetes.io/part-of: my-application-3
  name: my-application-3-nodejs-sample
  namespace: pshivpuj
spec:
  port:
    targetPort: 3001
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: my-application-3-nodejs-sample
    weight: 100
status: {}
